// src/components/containers/toolbar/index.tsx
import { Button } from '../../inputs/button';
import { LeftMenu } from '../../dialogs/left-menu';
import React from 'react';
import './toolbar.scss';
import './toolbar-mobile.scss';
import { BUSSINESS } from '../../../data';
import { Text } from '../../decorators/text';

export interface IToolbarItem {
  icon?: any,
  label: string,
  href?: string
}

export const Toolbar = (props: {
  items?: IToolbarItem[]
  rightItems?: any[]
  showLeftMenu?: boolean
  theme?: "light" | "dark"
}) => {

  return (
    <div className={`toolbar ${props.theme}`}>
      <div id="start_page" />
      <div className="left-box">
        {props.showLeftMenu && <LeftMenu />}
        <a href="/">
          {/* <img
            className="logo-img effect-opacity"
            src={BUSSINESS.logo}
            alt=""
          /> */}
          <Text className="logo-text" type="subtitle">Organize</Text>
        </a>
        {props.items && props.items.map((button, i) => {
          return (
            <Button
              style="text"
              key={i}
              href={button.href}
              className="toolbar-btn"
              label={`${button.label}`}
            />
          )
        })}
      </div>
      <div className="right-box">
        {props.rightItems && props.rightItems.map((item, i) => {
          return (
            <div key={i}>
              {item}
            </div>
          )
        })}
      </div>
    </div>
  );
};

// src/components/toolbar/toolbar.vue
<template v-cloak>
  <v-toolbar id="toolbar" fixed dark height="65px" v-if="!$store.state.drawer.left && !$store.getters.userLogged">
    <!-- LEFT MENU - BUTTON  -->
    <!-- <v-btn
      class="left-menu-btn d-flex d-sm-none"
      @click.native.stop="$store.commit('setLeftDrawer', true)"
      fab
      text
      small
    >
      <v-icon>menu</v-icon>
    </v-btn> -->

    <!-- LOGO  -->
    <v-toolbar-title @click.stop="pageRouter('/')">
      <!-- <img class="logo" src="@/assets/logo.png" @click.stop="pageRouter('/')" alt="Avatar" /> -->
      <h2 class="toolbar-title">Organize</h2>
    </v-toolbar-title>

    <div class="flex-grow-1"></div>

    <v-toolbar-items class="toolbar-items hidden-xs-only">
      <v-btn
        text
        small
        class="toolbar-button"
        v-for="(item, index) in filteredConf"
        :key="index"
        :href="item.href"
        :v-if="item.toolbar"
        @click="pageRouter(item.route)"
      >
        <v-icon>{{ item.icon }}</v-icon>
        <span>{{ item.name }}</span>
      </v-btn>
    </v-toolbar-items>

    <div class="right-box">
    </div>
  </v-toolbar>
</template>

<script lang="ts">
import ToolbarAction from "./toolbar.actions";
import "./toolbar.scss";
import { Watch, Component } from "vue-property-decorator";

@Component({
  components: {
  }
})
export default class Toolbar extends ToolbarAction {}
</script>
